#include <instructions.h>



int (*execute_instruction[NUM_OF_INSTRUCTIONS])(Resources *resources, TInstruction *instruction) = { 
        eq_int_reg_reg,
        eq_dbl_reg_reg,
        g_int_reg_reg,
        g_dbl_reg_reg,
        l_int_reg_reg,
        l_dbl_reg_reg,
        ge_int_reg_reg,
        ge_dbl_reg_reg,
        le_int_reg_reg,
        le_dbl_reg_reg,
        add_int_reg_reg,
        add_dbl_reg_reg,
        sub_int_reg_reg,
        sub_dbl_reg_reg,
        mul_int_reg_reg,
        mul_dbl_reg_reg,
        div_int_reg_reg,
        div_dbl_reg_reg,
        ne_int_reg_reg,
        ne_dbl_reg_reg,
        mov_int_reg,
        mov_int_const,
        mov_dbl_reg,
        mov_dbl_const,
        cast_int_reg,
        cast_int_const,
        cast_dbl_reg,
        cast_dbl_const,
        push_empty,
        push_int_const,
        push_dbl_const,
        push_index_const,
        push_int_reg,
        push_dbl_reg,
        push_index_reg,
        pop_empty,
        jmp_reg,
        jmp_const,
        jmp_true_reg_reg,
        jmp_true_const_const,
        jmp_true_const_reg,
        jmp_true_reg_const,
        function_call,
        function_return,
        halt
    };

